// GENERATED BY CODE! DO NOT MODIFY!
using UnityEngine;
namespace Watermelon
{
	[System.Serializable]
	public class Sounds
	{
		public AudioClip buttonSound;

		public AudioClip animalPickUpSound;
		public AudioClip itemPickUpSound;

		public AudioClip animalPlaceSound;
		public AudioClip animalCureSound;

		public AudioClip tableOpenSound;

		public AudioClip locationOpenSound;

		public AudioClip moneyPickUpSound;
		public AudioClip moneyPlaceSound;
	}
}